#!/bin/bash
for file in *.html
do
    # file already exists in parent directory and if it's older than the current file
    if [ ! -e "../$file" ] || [ "$file" -nt "../$file" ]
    then
        cp "$file" "../$file"
    fi
done
